<a href="https://colab.research.google.com/github/marvelxcodes/My-ML-Documentation/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **My Pytorch Notebook**

## 1. Importing Required Packages

In [39]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__) # Prints version of PyTorch

1.13.0+cu116


## 2. Creating Tensors

### 2.1 Creating Tensors - `torch.tensor()`

In [40]:
# Scalar - 0 dimension
scalar = torch.tensor(46)
print(scalar)
print(scalar.item())
print(scalar.ndim)
print(scalar.shape)
print(scalar.dtype)

tensor(46)
46
0
torch.Size([])
torch.int64


In [41]:
# Vector - 1 dimension
vector = torch.tensor([1, 2])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([1, 2])
1
torch.Size([2])


In [42]:
# Matrix - 2 dimension
MATRIX = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
2
torch.Size([3, 3])


In [43]:
# Tensor - 3 dimension
TENSOR = torch.tensor([[[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)
print(TENSOR.dtype)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
3
torch.Size([1, 3, 3])
torch.int64


### 2.2 Random Tensors - `torch.rand()`

In [44]:
RANDOM_TENSOR = torch.rand(4, 3)
print(RANDOM_TENSOR)
print(RANDOM_TENSOR.ndim)
print(RANDOM_TENSOR.shape)

tensor([[0.3877, 0.7956, 0.6423],
        [0.2403, 0.8434, 0.9984],
        [0.6953, 0.4697, 0.9120],
        [0.7909, 0.2537, 0.9592]])
2
torch.Size([4, 3])


### 2.3 Tensors with zeros - `torch.zeros()`

In [45]:
zeros = torch.zeros(3, 4)
print(zeros)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


### 2.4 Tensors with ones - `torch.ones()`

In [46]:
ones = torch.ones(3, 4)
print(ones)
print(ones.dtype)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32


### 2.5 Range of Tensors - `torch.arange()`

In [47]:
TENSOR_RANGE = torch.arange(1, 11, 2)
print(TENSOR_RANGE)

tensor([1, 3, 5, 7, 9])


### 2.6 Tensors Like - **torch.zeros_like/ones_like**

In [48]:
ZEROS_LIKE = torch.zeros_like(TENSOR_RANGE)
print(ZEROS_LIKE)

tensor([0, 0, 0, 0, 0])


## 3. Tensor Datatypes

### 3.1 Creating Tensor with explicit datatype - `torch.tensor(dtype=torch.float32)`

In [49]:
float32_tensor = torch.tensor([[1, 2, 3],
                               [4, 5, 6],
                               [7, 8, 9]],
                              dtype=torch.float32,
                              device=None, # cpu / cuda(gpu)
                              requires_grad=False)
print(float32_tensor)
print(float32_tensor.dtype)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
torch.float32


### 3.2 Type Conversion - `torch.tensor().type(torch.float16)`

In [50]:
float16_tensor = float32_tensor.type(torch.float16)
int64_tensor = float32_tensor.type(torch.int64)
long_tensor = float32_tensor.type(torch.long)

print(float16_tensor.dtype)
print(int64_tensor.dtype)
print(long_tensor.dtype)

torch.float16
torch.int64
torch.int64


### 3.3 Multiplying different DataTypes

In [52]:
print(float32_tensor*float16_tensor)
print(long_tensor*int64_tensor)
print(long_tensor*float32_tensor)

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])
tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])


## 4. Getting info of Tensor

In [58]:
RANDOM_TENSOR = torch.rand(3, 4)
print(f"Shape of Tensor : {RANDOM_TENSOR.shape}")
print(f"Device of Tensor : {RANDOM_TENSOR.device}")
print(f"Dtype of Tensor : {RANDOM_TENSOR.dtype}")

Shape of Tensor : torch.Size([3, 4])
Device of Tensor : cpu
Dtype of Tensor : torch.float32


## 5. Manipulating Tensors


In [68]:
tensor = torch.tensor([[
          [1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]
        ]])

### 5.1 Addition

In [74]:
# 5.1 Addition
print(tensor + 10)
print(tensor + tensor)
print(tensor + 2 + 3)
print(tensor + np.array([1, 2, 3])) # Normal list can't be added

tensor([[[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]]])
tensor([[[ 2,  4,  6],
         [ 8, 10, 12],
         [14, 16, 18]]])
tensor([[[ 6,  7,  8],
         [ 9, 10, 11],
         [12, 13, 14]]])
tensor([[[ 2,  4,  6],
         [ 5,  7,  9],
         [ 8, 10, 12]]])


### 5.2 Subtraction

### 5.3 Multiplication