<a href="https://colab.research.google.com/github/marvelxcodes/My-ML-Documentation/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **My Pytorch Notebook**

## 1. Importing Required Packages

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__) # Prints version of PyTorch

1.13.0+cu116


## 2. Creating Tensors

### 2.1 Creating Tensors - `torch.tensor()`

In [20]:
# Scalar - 0 dimension
scalar = torch.tensor(46)
print(scalar)
print(scalar.item())
print(scalar.ndim)
print(scalar.shape)
print(scalar.dtype)

tensor(46)
46
0
torch.Size([])
torch.int64


In [9]:
# Vector - 1 dimension
vector = torch.tensor([1, 2])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([1, 2])
1
torch.Size([2])


In [13]:
# Matrix - 2 dimension
MATRIX = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
2
torch.Size([3, 3])


In [21]:
# Tensor - 3 dimension
TENSOR = torch.tensor([[[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)
print(TENSOR.dtype)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
3
torch.Size([1, 3, 3])
torch.int64


### 2.2 Random Tensors - `torch.rand()`

In [13]:
RANDOM_TENSOR = torch.rand(4, 3)
print(RANDOM_TENSOR)
print(RANDOM_TENSOR.ndim)
print(RANDOM_TENSOR.shape)

tensor([[0.8115, 0.9486, 0.5309],
        [0.4378, 0.3579, 0.4711],
        [0.1471, 0.9804, 0.3021],
        [0.7714, 0.6936, 0.8398]])
2
torch.Size([4, 3])


### 2.3 Tensors with zeros - `torch.zeros()`

In [15]:
zeros = torch.zeros(3, 4)
print(zeros)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


### 2.4 Tensors with ones - `torch.ones()`

In [23]:
ones = torch.ones(3, 4)
print(ones)
print(ones.dtype)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32


### 2.5 Range of Tensors - `torch.arange()`

In [25]:
TENSOR_RANGE = torch.arange(1, 11, 2)
print(TENSOR_RANGE)

tensor([1, 3, 5, 7, 9])


### 2.6 Tensors Like - **torch.zeros_like/ones_like**

In [27]:
ZEROS_LIKE = torch.zeros_like(TENSOR_RANGE)
print(ZEROS_LIKE)

tensor([0, 0, 0, 0, 0])


## Tensor Datatypes

### 3.1 Creating Tensor with explicit datatype - `torch.tensor(dtype=torch.float32)`

In [32]:
float32_tensor = torch.tensor([[1, 2, 3],
                               [4, 5, 6],
                               [7, 8, 9]],
                              dtype=torch.float32,
                              device=None, # cpu / cuda(gpu)
                              requires_grad=False)
print(float32_tensor)
print(float32_tensor.dtype)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
torch.float32


### 3.2 Type Conversion - `torch.tensor().type(torch.float16)`

In [35]:
float16_tensor = float32_tensor.type(torch.float16)
print(float16_tensor.dtype)

torch.float16
