<a href="https://colab.research.google.com/github/marvelxcodes/My-ML-Documentation/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **My Pytorch Notebook**

## 1. Importing Required Packages

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__) # Prints version of PyTorch

1.13.0+cu116


## 2. Introduction to Tensors

### 2.1 Creating Tensors

In [8]:
# Scalar
scalar = torch.tensor(46)
print(scalar)
print(scalar.item())
print(scalar.ndim)
print(scalar.shape)

tensor(46)
46
0
torch.Size([])


In [9]:
# Vector
vector = torch.tensor([1, 2])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([1, 2])
1
torch.Size([2])


In [13]:
# Matrix
MATRIX = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
2
torch.Size([3, 3])


In [15]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
3
torch.Size([1, 3, 3])


### 2.2 Random Tensors